### ISSUE TITLE
Add Class Inheritance

### ISSUE THREAD

**Issue by logan-r** [logan-r/vilify#90]
Classes should inherit from superclasses in order to avoid repeat code. The top level object should be `GameObject` which has the children `Item` and `PhysicalObject`. `PhysicalObject` should have the children `AnimateObject` and `Tower`. `AnimateObject` should have the children `FightingObject` and `Projectile`. `FightingObject` should have the children `Hero` and `Monster`

**Comment by sru** [comment]
How are you going to do the inheritance? What specific way?

**Comment by logan-r** [comment]
I was planning on making a subclass inherit from a superclass by having the child class use its parent class's model, view, and control objects as the base for its own model, view, and control objects. See b085cb4ae300230c7ebf668e338a142ef8cdada7
